
default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

  username: postgres
  password: 0N1namak0
  host: localhost
  port: 5432



development:
  <<: *default
  database: postgresSample_development

test:
  <<: *default
  database: postgresSample_test

production:
  <<: *default
