
default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: postgresSample_development
  username: postgres
  password: 0N1namak0
  host: localhost
  port: 5432

test:
  <<: *default
  database: postgresSample_test
  username: postgres
  password: 0N1namak0
  host: localhost
  port: 5432
  
production:
  <<: *default
  database: d8to9ht565kti3
  username: btgnyctgunoick
  password: a0bc4006bf1cd952f5518eb1217eff1cc55660b1c57d89f458f4b088a2c558a1
  host: ec2-18-214-211-47.compute-1.amazonaws.com
  port: 5432
